### ISSUE TITLE
Plugin crashes on `write` if another response comes

### ISSUE THREAD

**Issue by andrews1-digital** [NeuraLegion/cypress-har-generator#100]
We run multiple (50+) Cypress (v10.7.0) executions concurrently via Github actions.
On a move from 5.3.0 to 5.3.3 we intermittently get the following error
```
Your configFile threw an error from: cypress.config.js

We stopped running your tests because your config file crashed.

TypeError: Cannot read properties of undefined (reading 'write')
    at t.Plugin.<anonymous> (<path>/node_modules/@neuralegion/cypress-har-generator/dist/index.js:1:2252)
    at Generator.next (<anonymous>)
    at fulfilled (<path>/node_modules/tslib/tslib.js:115:62)
```

On reverting to 5.3.0 we have not seen the error.

**Comment by derevnjuk** [comment]
The fix has been released in v5.3.4. Please verify it as soon as you have time. Feel free to reopen the issue if the bug is still there
