### ISSUE TITLE
recordHar() is not starting to record during a run

### ISSUE THREAD

**Issue by cristina-boop** [NeuraLegion/cypress-har-generator#101]
On cypress.config.ts
![image](https://user-images.githubusercontent.com/78798938/197524100-e3279ec2-87a8-4b2e-98da-5bb2745616cf.png)
![image](https://user-images.githubusercontent.com/78798938/197524171-63a13769-b6e3-42c1-a988-0efd928c7acf.png)
![image](https://user-images.githubusercontent.com/78798938/197524226-b27a2fe4-93a6-4c1c-a86b-c167b20bb625.png)
But when I start a headless run, the record command is not working.( npx cypress run --spec **/accessAsset.spec.ts --browser chrome --headless)

- cypress 10.09 version
- node.js 16.4
- chrome version 106

![image](https://user-images.githubusercontent.com/78798938/197524499-81c0f163-404c-429b-9fa0-9473876b3a59.png)

**Comment by derevnjuk** [comment]
@cristina-boop could you provide a reproducible repository?

**Comment by derevnjuk** [comment]
@nfelger please provide a reproducible repository if it is possible

**Comment by derevnjuk** [comment]
@cristina-boop, could you ensure that the on("before:browser:launch") is invoked at the end of the `setupNodeEvents` method? I believe this may be related to the issue discussed at https://github.com/cypress-io/cypress/issues/5240.
