### ISSUE TITLE
xhr type request with a warning type request not record in har file

### ISSUE THREAD

**Issue by aaujayasena** [NeuraLegion/cypress-har-generator#107]
I observed xhr type request with a warning not record in har file generated from this plugin.  But this  request are critically important when analysing a test failures. 

![image](https://user-images.githubusercontent.com/39077751/203256722-8d08c29b-aac4-4245-a4e1-f9c1206ce846.png)

But this is recording when cypress test execution with UI interaction mode and "chromeWebSecurity": true and download the har file manually. But "chromeWebSecurity": true and  execute heedless mode couldn't capture these request. 

Please let me know if there is a way to get the details of an xhr request into the har file with  chromeWebSecurity": false and  headless mode using this plugin. 

Appreciate your suggestions.

**Comment by derevnjuk** [comment]
@aaujayasena can you please clarify how this request was made? Did you use `cy.visit` or `cy.request` to issue it? I would appreciate it if you provide a HAR file containing this entry.

**Comment by derevnjuk** [comment]
@aaujayasena Could you please share more information so I can better understand the issue? I am currently unable to reproduce the same behavior.
