### ISSUE TITLE
saveHar ignores directory path

### ISSUE THREAD

**Issue by bartonhammond** [NeuraLegion/cypress-har-generator#178]
**Description**
Using `    "@neuralegion/cypress-har-generator": "^5.14.0",`

Try to save the file in a path that is determined at run time.  
Here `harPath` is `admin/blockScheduling/officerSetup/` & `harFIleName` is `'User-needs-to-set-up-an-officer-and-assign-them-to-a-specific-group-dev-chrome.har'`

The full path was created before the `saveHar`
![image](https://user-images.githubusercontent.com/1282364/214870195-50b24033-fdd0-4b19-a381-661c0d241890.png)

File saved to root ignoring path
![image](https://user-images.githubusercontent.com/1282364/214870752-8d2e42c2-6d49-4fb1-9ceb-1f2f129f994d.png)

Debugger showing harPath
![image](https://user-images.githubusercontent.com/1282364/214869714-40e6d214-dcf5-4df0-972d-02f19cbbf116.png)

```
   cy.saveHar({
          fileName: `/${harPath}/${harFileName}`
        });
```
The env is setup
```
env: {
  "hars_folders": "cypress/hars"
}
```

**Steps to reproduce**
1. try to save a file to a sub directory below the `hars_folders`

**Expected behavior**
HAR file created in subdirectory

**Actual behavior**
HAR file created in `hars_folder` ignoring the subdirectory path

**Screenshots**
See above

**Comment by derevnjuk** [comment]
@bartonhammond thanks for the report 👍🏾 `fileName` is the name of the file in the pathname (for details please refer to [basename](https://man7.org/linux/man-pages/man3/basename.3.html)), the directory will be ignored by design. If you want to change the destination folder programmatically, you can use the `outDir` option as follows:

```js
cy.saveHar({ outDir: harPath, fileName: harFileName })
```

**Comment by bartonhammond** [comment]
@derevnjuk  Thanks for the help.

The file isn't written out at all now.  Stopping in the debugger I see the values are set correctly but the `outDir` directory is empty.

![image](https://user-images.githubusercontent.com/1282364/214886822-2282fac2-e8c5-4b3f-9b5e-b2139238140b.png)

**Comment by bartonhammond** [comment]
Needed the entire path

```
let harsFolder = Cypress.env("hars_folders");
let harPath = "admin/blockScheduling/officerSetup/";
let harFileName = `${scenarioName}-${env}-${browser}.har`

 cy.saveHar({
    outDir: `${harsFolder}/${harPath}`, 
    fileName: harFileName,
  });
```
