### ISSUE TITLE
Generate a separate HAR file per-test

### ISSUE THREAD

**Issue by Osmose** [NeuraLegion/cypress-har-generator#22]
Hi! Thanks for making this library, it's exactly what we were looking for!

Would it be possible to generate a separate HAR file for each individual spec file? The single HAR file our tests are generating is pretty large and hard to inspect.

**Comment by ArtemDerevnjuk** [comment]
Hi @Osmose , thanks for your question. Yep, it's possible. In general, the plugin is already doing this. We just need to provide a simple interface for the end-user.
