### ISSUE TITLE
Not working in ESM mode

### ISSUE THREAD

**Issue by MohamadKh75** [NeuraLegion/cypress-har-generator#308]
**Description**
My project is using `ESM` (`"type": "module"`) and it's not working.

**Stack trace**

```
import { install as harGenerator } from '@neuralegion/cypress-har-generator';
         ^^^^^^^
SyntaxError: Named export 'install' not found. The requested module '@neuralegion/cypress-har-generator' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@neuralegion/cypress-har-generator';
const { install: harGenerator } = pkg;
```

And when I try to use the above:

```
No default export found in imported module "@neuralegion/cypress-har-generator".
InvalidEventHandlerError: The handler for the event `task` must be an object
```

I tried to use it in this way:

```
// eslint-disable-next-line import/default
import pkg from '@neuralegion/cypress-har-generator';

pkg.install(on);
```

but then I get this error in the runtime:

```
🍑 Error: ENOENT: no such file or directory, mkdir 'cypress/reports/har'
🍑 Error: ENOENT: no such file or directory, open 'cypress/reports/har/base.cy.har'
```

I already have `cypress/reports/har` so It's a false error!

**Steps to reproduce**

1. Use Cypress in ESM mode
2. Install this plugin and set it up
3. Not working

**Expected behavior**
To be okay

**Actual behavior**
It's not working

**Comment by MohamadKh75** [comment]
Well, I investigated and the problem is when I'm using `hars_folders: 'cypress/reports/har'` in my config file.
I know you mentioned the path is relative but I think it must be absolute or at least there should be an option to set the root directory (I used `rootDir` in the `recordHar` but no result!

**Comment by parkuman** [comment]
still experiencing this issue, particularly when trying to use `cypress-debugger` (which uses this package. Have made an [issue here](https://github.com/currents-dev/cypress-debugger/issues/79)
