### ISSUE TITLE
Ability to not capture content

### ISSUE THREAD

**Issue by Stono** [NeuraLegion/cypress-har-generator#35]
Hey there!
Thanks for this awesome plugin.

I'm wondering if it would be possible to have the option to disable the capturing of the content in the HAR file.

I'm actually only interested in the timings and the headers, by omitting the content i would save on the size of my har files by an order of magnitude.

Does this make sense?

Would we just need something conditional around: https://github.com/NeuraLegion/cypress-har-generator/blob/e437e87879f97334f6ab95a627fe4dde1deb2d64/src/network/NetworkObserver.ts#L412 ?

Thanks
Karl

**Comment by derevnjuk** [comment]
Hey @Stono, 

Thanks for your advice) I'll see what we can do. Maybe, we can introduce a parameter for `recordHar` method. I would propose this:

```typescript
public recordHar(options: { content: boolean }): Chainable<Subject>;
```

**Comment by Stono** [comment]
That would be amazing @derevnjuk :)

**Comment by Stono** [comment]
Mega!! Thanks! :)

**Comment by Stono** [comment]
Maybe got a problem @derevnjuk after upgrading:

![Screenshot 2020-04-27 at 14 30 15](https://user-images.githubusercontent.com/1486729/80377884-bff07b80-8893-11ea-90ec-247d49d1bd97.png)

**Comment by Stono** [comment]
Never mind, it was user error.  Thanks again for your work!

**Comment by derevnjuk** [comment]
@Stono If you have any questions, feel free to ask)
