### ISSUE TITLE
does not work with cypress tests written in Typescript

### ISSUE THREAD

**Issue by mattmbrightside** [NeuraLegion/cypress-har-generator#38]
Does this plugin work with cypress tests written in Typescript? 

package.json
    "@neuralegion/cypress-har-generator": "^5.0.0",

commands.ts
import '@neuralegion/cypress-har-generator/commands';

index.js
const { install, ensureBrowserFlags } = require('@neuralegion/cypress-har-generator');

const { preprocessTypescript } = require('@nrwl/cypress/plugins/preprocessor');

module.exports = (on, config) => {
  install(on, config);

  on('before:browser:launch', (browser = {}, launchOptions) => {
    ensureBrowserFlags(browser, launchOptions);
    return launchOptions;
  });

  // `on` is used to hook into various events Cypress emits
  // `config` is the resolved Cypress config

  // Preprocess Typescript
  on('file:preprocessor', preprocessTypescript(config));
};

my.spec.ts
describe('my test', () => {
  before(() => {
    // start recording
    cy.recordHar();
  });

  after(() => {
    // HAR will be saved as users.spec.har
    // at the root of the project
    cy.saveHar();
  });

On the recordHar line I get
TS2339: Property 'recordHar' does not exist on type 'cy & EventEmitter'.

**Comment by derevnjuk** [comment]
Hi @mattmbrightside, to make `tsc` include type declaration files in the compilation you need to specify `types` in `compilerOptions`:

```js
{
  "compilerOptions": {
    // ...
    "types": [
      "cypress",
      "@neuralegion/cypress-har-generator"
    ]
  }
}
```

**Comment by mattmbrightside** [comment]
Thank you!!!!

After I added your library to the tsconfig I also had to update cypress to the latest 4.5.0 (was on 3.8.0) and then I could run my test and generate a HAR file.
