### ISSUE TITLE
Can I use this plugin to get a HAR file from the Cypress session itself, rather than the browser instance of each test?

### ISSUE THREAD

**Issue by henricook** [NeuraLegion/cypress-har-generator#402]
**Description**
I'm trying to diagnose an issue where a setup call made by Cypress itself (cy.callAPI) is failing. It would be helpful  if I could get a HAR file for callAPI requests too, is this plugin capable of that?

**Comment by derevnjuk** [comment]
@henricook Thanks for the question. Unfortunately, it's not currently possible, as the plugin only listens to browser network traffic and cannot intercept requests made directly by Cypress. Duplicate of https://github.com/NeuraLegion/cypress-har-generator/issues/59
