### ISSUE TITLE
Previous network entries should be cleared when cy.recordHar() is called again

### ISSUE THREAD

**Issue by olyhaa-aetna** [NeuraLegion/cypress-har-generator#42]
I currently have two Cypress spec files and I want to record a separate HAR file for each file. I have added `cy.recordHar()` and `cy.saveHar()` in the `before()` and `after()` for each test file as suggested.

In addition, I only want to save the HAR on failure, so I only call `cy.saveHar()` if at least one of the tests in the appropriate spec file fails.

If each spec file has an error, I get two HAR files, each containing only the network requests from that test. This is working as expected.

However, if the first spec file has no failures, but the second spec file has a failure, I'm seeing all network requests from **both** spec files in the generated HAR file.  I want the generated HAR file to only contain network requests from the tests in the second spec file.

When calling `cy.recordHar()` I would expect any previously recorded network entries to be cleared. It appears that this may not be happening.

**Comment by derevnjuk** [comment]
As far I know entries are cleared while calling `saveHar` command. I'll fix it in the next release.

**Comment by kalpeshchilka** [comment]
@derevnjuk For now, is there any workaround for this issue. I am also facing a similar issue, like if I add `cy.recordHar();` and `cy.saveHar();` in **first** `it()` and again call `cy.recordHar();` and `cy.saveHar();` in **second** `it()`. Second har file generated consists of data from **`beforeEach()`** and also from first `it()`.
