### ISSUE TITLE
Firefox doesn't support Security and Network domain properly

### ISSUE THREAD

**Issue by derevnjuk** [NeuraLegion/cypress-har-generator#6]
Firefox is still implementing the DevTools protocol. I hope guys will fix the shortcomings soon.
You can follow updates by the link: 

https://bugzilla.mozilla.org/buglist.cgi?product=Remote%20Protocol&component=Network&bug_status=__open__

**Comment by digitarald** [comment]
@ArtemDerevnjuk hi there, DevTools member here. Could this work be done without CDP, using HAR extension API, using https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network/getHAR ?

**Comment by ArtemDerevnjuk** [comment]
Hi @digitarald, wonderful to see you here! I guess it's possible. Cypress allows installing a browser extension during  `before:browser:launch` hook. However, CDP provides low-level API to manage network events which make life so much easier in handling cypress stubs. How much time will it take your team to fully support the latest version of the protocol (https://chromedevtools.github.io/devtools-protocol/tot)?

**Comment by digitarald** [comment]
@ArtemDerevnjuk could you list which CDP APIs do you depend on?

**Comment by ArtemDerevnjuk** [comment]
@digitarald As I noticed in Bugzilla only `requestWillBeSent` has been implemented.
The following list details each of the necessary network events (including optional):

* [requestWillBeSent](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-requestWillBeSent)
* [dataReceived](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-dataReceived)
* [responseReceived](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-responseReceived)
* [loadingFinished](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-loadingFinished)
* [loadingFailed](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-loadingFailed)
* [webSocketCreated](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-webSocketCreated)
* [webSocketWillSendHandshakeRequest](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-webSocketWillSendHandshakeRequest)
* [webSocketHandshakeResponseReceived](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-webSocketHandshakeResponseReceived)
* [webSocketFrameSent](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-webSocketFrameSent)
* [webSocketFrameReceived](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-webSocketFrameReceived)
* [webSocketFrameError](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-webSocketFrameError)
* [webSocketClosed](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-webSocketClosed)

Maybe I could help you to implement them.

**Comment by digitarald** [comment]
Thank you @ArtemDerevnjuk , we are tracking those dependencies in https://bugzilla.mozilla.org/show_bug.cgi?id=1605512

**Comment by digitarald** [comment]
> Maybe I could help you to implement them.

In case anybody wants to help, the team is hanging out in [Firefox's DevTools Slack](http://devtools-html-slack.herokuapp.com/)'s `#remote` channel.

**Comment by Sija** [comment]
@digitarald Hi, any news re: the progress?

**Comment by derevnjuk** [comment]
This is no longer relevant as we are investigating the ability to use [BiDi](https://w3c.github.io/webdriver-bidi/) instead of CDP. Closing this in favor of a more general issue: https://github.com/NeuraLegion/cypress-har-generator/issues/5.

For more details, please refer to: https://bugzilla.mozilla.org/show_bug.cgi?id=1605512
