### ISSUE TITLE
Add ability to record content only when 4xx or 5xx status code

### ISSUE THREAD

**Issue by johnslay** [NeuraLegion/cypress-har-generator#65]
It would be nice if recordHar was configureable as to what we could record, for example:

```
  cy.recordHar({
    content: 'on-failure'
  });
 ```

Ideally, we could make this more configurable as people see fit, but I'd like to start off with only checking for 5xx or 4xx error codes and record only the content for those.

**Comment by derevnjuk** [comment]
@johnslay  thank you for your contribution. To clarify, by the following option, are you expecting the plugin to exclude requests from the HTTP Archive (HAR) file entirely, or just omit the response content (aka response body) for those requests?
