### ISSUE TITLE
No clear documentation about configuring the folder to store har files

### ISSUE THREAD

**Issue by jdvegmond** [NeuraLegion/cypress-har-generator#66]
In the readme it mentions the following:

Pass an output directory to change the destination folder manually. It allows overriding the value, that is specified in the `cypress.json`

```js
cy.saveHar({ outDir: './hars' });
```

But it's not clear how the folder can be specified in the `cypress.json`. Please make this more clear.

**Comment by derevnjuk** [comment]
@jdvegmond Sorry for the delay, and thanks for the question. The document has been updated (see #93). Let me know if you have any questions.
