### ISSUE TITLE
[ERROR] The plugins file is missing or invalid.

### ISSUE THREAD

**Issue by nfseixas** [NeuraLegion/cypress-har-generator#8]
Hello, 

First of all, thank you so much for your solution. It'll help me a lot since I’ve been trying to export my HAR for a few months! 

I've followed all of ReadMe instructions and I can’t sort it out a problem which is happening every time when Cypress is about to be loaded, I was wondering if someone can help me to find out what's going on. 
![ERROR HARExport](https://user-images.githubusercontent.com/16138846/70568874-871b6880-1b77-11ea-807f-f91f9d351c35.png)

I’m looking forward to hearing from you

Thank you so much in advance

**Comment by ArtemDerevnjuk** [comment]
Hi @nfseixas ,

Thanks for your interest in our solution)

As far as I can see I missed `tslib` in `package.json` for some reason. The problem is here ;) I'll publish a patch asap.
